import Navbar from '@/components/navbar';
import './globals.css';
import Wrapper from '@/Provider';

export const metadata = {
  title: 'Shop Sphere',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Wrapper>
          <Navbar />
          <main>{children}</main>
        </Wrapper>
      </body>
    </html>
  );
}
